### ISSUE TITLE
Desktop: file not created

### ISSUE THREAD

**Issue by PaulDGillis** [zacharee/KMPFile#2]
Similar to the iOS issue #1, I'm using `val file = FileUtils.fromString(filePath, false)` on jvm desktop. This function always returns null for me.

**Comment by zacharee** [comment]
This should be fixed in 0.6.2

**Comment by PaulDGillis** [comment]
Thank you for fixing it so quickly! It does indeed fix the issue. Parsing file paths works perfectly on Android/Jvm Desktop. However I did run into an issue on iOS when using the Filekit extension PlatformDirectory.toKMPFile(), but I'll open a separate issue.
