### ISSUE TITLE
Filekit extension PlatformDirectory.toKMPFile

### ISSUE THREAD

**Issue by PaulDGillis** [zacharee/KMPFile#3]
When using `PlatformDirectory.toKMPFile()` it returns null, nsURL from Filekit itself is null. I'm unclear if this is only on the Simulator, I'm unable to test on a physical iPhone.

**Comment by zacharee** [comment]
It shouldn't be possible for `toKMPFile()` to return null. `PlatformDirectory` is just a class containing a non-null NSURL.

**Comment by PaulDGillis** [comment]
You're right, my apologizes. I saw that when reading through both projects source last night. From breakpoints, I was getting nsURL as null or empty. May be from my environment, I've been struggling to find a consistent way to debug iOS Kotlin native.
